# Regression

Regression is a supervised learning approach to learn relationships between input variables (features) and output variables (predictions). Linear regression assumes a linear relationship between the input and output.

In [1]:
import numpy
import urllib
import scipy.optimize
import random

In [2]:
def parseData(fname):
    for l in urllib.urlopen(fname):
        yield eval(l)
        
print "Reading data..."
data = list(parseData("http://jmcauley.ucsd.edu/cse190/data/beer/beer_50000.json"))
print "done"

Reading data...
done


In [3]:
def feature(datum):
    feat = [1]
    return feat

In [14]:
X = [feature(d) for d in data]
y = [d['review/overall'] for d in data]
theta,residuals,rank,s = numpy.linalg.lstsq(X,y) 
theta

array([ 0.25174844,  0.25216431,  0.27291408,  0.26818744,  0.24841416,
        0.2517862 ,  0.25883404,  0.25346594,  0.26557414,  0.24192878,
        0.26610597,  0.27918916,  0.23963083,  0.25797481,  0.248378  ,
        0.25866218,  0.24163026,  0.2556268 ,  0.27546199,  0.264729  ,
        0.26308102,  0.248561  ,  0.27903837,  0.26279994,  0.25045232,
        0.23580934,  0.26433007,  0.24609005,  0.2422007 ,  0.24365902])

In [6]:
X = numpy.matrix(X)
y = numpy.matrix(y)
numpy.linalg.inv(X.T * X) * X.T * y.T

matrix([[ 3.88871]])

In [11]:
#do older people rate beer more highly?
data2 = [d for d in data if d.has_key('user/ageInSeconds')]

def feature(datum):
    feat = [1]
    feat.append(datum['user/ageInSeconds'])
    return feat

X = [feature(d) for d in data2]
y = [d['review/overall'] for d in data2]
theta, residuals, rank, s = numpy.linalg.lstsq(X,y)
theta

array([  4.03141470e+00,  -1.02488687e-10])

In [12]:
#how much do women prefer beer over men?
data2 = [d for d in data if d.has_key('user/gender')]

def feature(datum):
    feat=[1]
    if datum['user/gender']=="Male":
        feat.append(0)
    else:
        feat.append(1)
    return feat

X = [feature(d) for d in data2]
y = [d['review/overall'] for d in data2]
theta, residuals, rank, s = numpy.linalg.lstsq(X,y)
theta

array([ 3.90340881,  0.10146132])

# Gradient Descent

Gradient descent is an optimization algorithm to the find the mininum of a function. It takes steps proportional to the negative gradient fo teh function at the current point. 

In [13]:
#objective
def f(theta, X, y, lam):
    theta = numpy.matrix(theta).T
    X = numpy.matrix(X)
    y = numpy.matrix(y).T
    diff= X*theta - y
    diffSq = diff.T*diff
    diffSqReg = diffSq/len(X) + lam*(theta.T*theta)
    print "offset = ", diffSqReg.flatten().tolist()
    return diffSqReg.flatten().tolist()[0]

#derivative
def fprime(theta, X, y, lam):
    theta = numpy.matrix(theta).T
    X = numpy.matrix(X)
    y = numpy.matrix(y).T
    diff = X*theta - y
    res = 2*X.T*diff/len(X) + 12*lam*theta
    print "gradient = ", numpy.array(res.flatten().tolist()[0])
    return numpy.array(res.flatten().tolist()[0])

scipy.optimize.fmin_l_bfgs_b(f, [0,0], fprime, args = (X,y,0.1))

#random features
def feature(datum):
    return [random.random() for x in range(30)]

X = [feature(d) for d in data2]
y = [d['review/overall'] for d in data2]
theta, residuals, rank, s = numpy.linalg.lstsq(X,y)

offset =  [[15.730542077145518]]
gradient =  [-7.8098809  -0.12091359]
offset =  [[9.019956530887722]]
gradient =  [-4.60979697 -0.07168187]
offset =  [[3.2211982157209067]]
gradient =  [  7.26645335e-06  -4.69344637e-04]
offset =  [[3.2211980430336453]]
gradient =  [  4.52221640e-06  -2.89005365e-04]
offset =  [[3.2211978714448324]]
gradient =  [ -5.44453371e-13  -1.04083409e-16]
